// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.service;

import java.time.LocalDate;
import java.time.ZonedDateTime;
import java.time.ZoneId;
import java.util.List;

import at.bestsolution.quti.calendar.service.model.Event;
import at.bestsolution.quti.calendar.service.model.EventNew;
import at.bestsolution.quti.calendar.service.model.EventSearch;

public interface EventService {
	public String create(BuilderFactory _factory, String calendar, EventNew.Data event)
			throws NotFoundException,
			InvalidArgumentException;

	public Event.Data get(BuilderFactory _factory, String calendar, String key, ZoneId timezone)
			throws NotFoundException,
			InvalidArgumentException;

	public List<Event.Data> search(BuilderFactory _factory, String calendar, EventSearch.Data filter, ZoneId timezone)
			throws InvalidArgumentException;

	public void update(BuilderFactory _factory, String calendar, String key, Event.Patch changes)
			throws NotFoundException,
			InvalidArgumentException;

	public void delete(BuilderFactory _factory, String calendar, String key);

	public void cancel(BuilderFactory _factory, String calendar, String key);

	public void uncancel(BuilderFactory _factory, String calendar, String key);

	public void move(BuilderFactory _factory, String calendar, String key, ZonedDateTime start, ZonedDateTime end);

	public void endRepeat(BuilderFactory _factory, String calendar, String key, LocalDate end);

	public void description(BuilderFactory _factory, String calendar, String key, String description);

}
