// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.service;

public class NotFoundException extends RSDException {
	public NotFoundException(String message) {
		super(Type.NotFound, message);
	}
}
