// Generated by RSD - Do not modify
package at.bestsolution.quti.service.model;

import java.time.ZonedDateTime;
import java.util.List;

import at.bestsolution.quti.service.model.mixins.EventViewDataMixin;

public interface EventView {
	public interface Data extends EventView {
		public String calendarKey();

		public String title();

		public String description();

		public String owner();

		public EventViewDataMixin.Status status();

		public ZonedDateTime start();

		public ZonedDateTime end();

		public List<String> tags();

		public List<String> referencedCalendars();

	}

	public interface DataBuilder {
	}
}
