// Generated by RSD - Do not modify
package at.bestsolution.quti.service.model;

import java.time.LocalDate;
import java.time.Month;
import java.time.ZoneId;
import java.util.Optional;

import at.bestsolution.quti.service.model.mixins.EventRepeatDataMixin;

public interface EventRepeatAbsoluteYearly {

	public interface Data extends _Base.BaseData, EventRepeatAbsoluteYearly, EventRepeatDataMixin, EventRepeat.Data {
		public short dayOfMonth();

		public Month month();

		public short interval();

		public LocalDate endDate();

		public ZoneId timeZone();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<EventRepeatAbsoluteYearly.Data>, EventRepeat.DataBuilder {
		public DataBuilder dayOfMonth(short dayOfMonth);

		public DataBuilder month(Month month);

		public DataBuilder interval(short interval);

		public DataBuilder endDate(LocalDate endDate);

		public DataBuilder timeZone(ZoneId timeZone);

	}

	public interface Patch extends _Base.BaseData, EventRepeatAbsoluteYearly {
		public Optional<Short> dayOfMonth();

		public Optional<Month> month();

		public Optional<Short> interval();

		public _Base.Nillable<LocalDate> endDate();

		public Optional<ZoneId> timeZone();

	}

	public interface PatchBuilder extends _Base.BaseDataBuilder<EventRepeatAbsoluteYearly.Patch> {
		public PatchBuilder dayOfMonth(short dayOfMonth);

		public PatchBuilder month(Month month);

		public PatchBuilder interval(short interval);

		public PatchBuilder endDate(LocalDate endDate);

		public PatchBuilder timeZone(ZoneId timeZone);

	}
}