// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.service.impl;

import java.time.LocalDate;
import java.time.ZonedDateTime;
import java.time.ZoneId;
import java.util.List;

import jakarta.enterprise.context.ApplicationScoped;

import at.bestsolution.quti.calendar.service.BuilderFactory;
import at.bestsolution.quti.calendar.service.CalendarService;
import at.bestsolution.quti.calendar.service.InvalidArgumentException;
import at.bestsolution.quti.calendar.service.InvalidContentException;
import at.bestsolution.quti.calendar.service.model.Calendar;
import at.bestsolution.quti.calendar.service.model.CalendarNew;
import at.bestsolution.quti.calendar.service.model.EventView;
import at.bestsolution.quti.calendar.service.NotFoundException;

@ApplicationScoped
public class CalendarServiceImpl implements CalendarService {
	private final CreateHandler createHandler;
	private final GetHandler getHandler;
	private final UpdateHandler updateHandler;
	private final EventViewHandler eventViewHandler;
	private final CloseHandler closeHandler;

	public CalendarServiceImpl(CreateHandler createHandler, GetHandler getHandler, UpdateHandler updateHandler, EventViewHandler eventViewHandler, CloseHandler closeHandler) {
		this.createHandler = createHandler;
		this.getHandler = getHandler;
		this.updateHandler = updateHandler;
		this.eventViewHandler = eventViewHandler;
		this.closeHandler = closeHandler;
	}

	@Override
	public String create(BuilderFactory _factory, CalendarNew.Data calendar)
			throws InvalidContentException {
		return createHandler.create(_factory, calendar);
	}

	@Override
	public Calendar.Data get(BuilderFactory _factory, String key)
			throws NotFoundException,
			InvalidArgumentException {
		return getHandler.get(_factory, key);
	}

	@Override
	public void update(BuilderFactory _factory, String key, Calendar.Patch changes)
			throws NotFoundException,
			InvalidArgumentException {
		updateHandler.update(_factory, key, changes);
	}

	@Override
	public List<EventView.Data> eventView(BuilderFactory _factory, String key, LocalDate start, LocalDate end, ZoneId timezone, ZoneId resultTimeZone)
			throws NotFoundException,
			InvalidArgumentException {
		return eventViewHandler.eventView(_factory, key, start, end, timezone, resultTimeZone);
	}

	@Override
	public void close(BuilderFactory _factory, String key, ZonedDateTime date)
			throws NotFoundException,
			InvalidArgumentException {
		closeHandler.close(_factory, key, date);
	}

	public interface CreateHandler {
		public String create(BuilderFactory _factory, CalendarNew.Data calendar)
				throws InvalidContentException;
	}

	public interface GetHandler {
		public Calendar.Data get(BuilderFactory _factory, String key)
				throws NotFoundException,
				InvalidArgumentException;
	}

	public interface UpdateHandler {
		public void update(BuilderFactory _factory, String key, Calendar.Patch changes)
				throws NotFoundException,
				InvalidArgumentException;
	}

	public interface EventViewHandler {
		public List<EventView.Data> eventView(BuilderFactory _factory, String key, LocalDate start, LocalDate end, ZoneId timezone, ZoneId resultTimeZone)
				throws NotFoundException,
				InvalidArgumentException;
	}

	public interface CloseHandler {
		public void close(BuilderFactory _factory, String key, ZonedDateTime date)
				throws NotFoundException,
				InvalidArgumentException;
	}

}
