// Generated by RSD - Do not modify
package at.bestsolution.quti.service;

import at.bestsolution.quti.service.model._Base;

public interface BuilderFactory {
	public <T extends _Base.BaseDataBuilder<?>> T builder(Class<T> type);
}