// Generated by RSD - Do not modify
package at.bestsolution.quti.service.dto;

public interface BaseDTO {
		public static record Nilable<T>(T value) {

		}
    public interface Builder {
        public BaseDTO build();
    }
}
