// Generated by RSD - Do not modify
package at.bestsolution.quti.service.dto;

public interface CalendarDTO extends BaseDTO {
    /**
     * Unique identifier of the calendar
     */
    public String key();
    /**
     * Name of the calendar
     */
    public String name();
    /**
     * Owner of the calendar
     */
    public String owner();

    public interface Builder extends BaseDTO.Builder {
        public Builder key(String key);
        public Builder name(String name);
        public Builder owner(String owner);
        public CalendarDTO build();
    }
}
