// Generated by RSD - Do not modify
package at.bestsolution.quti.service.dto;

import java.util.function.Consumer;

public interface CalendarDTO extends BaseDTO {
    /**
     * Unique identifier of the calendar
     */
    public String key();
    /**
     * Name of the calendar
     */
    public String name();
    /**
     * Owner of the calendar
     */
    public String owner();

    public interface Builder extends BaseDTO.Builder {
        public Builder key(String key);
        public Builder name(String name);
        public Builder owner(String owner);
        public CalendarDTO build();
    }

		public interface Patch {
			public String key();
			public String name();
			public String owner();

			public static void ifName(Patch dto, Consumer<String> consumer) {
				if( dto.name() != null ) {
					consumer.accept(dto.name());
				}
			}

			public static void ifOwner(Patch dto, Consumer<String> consumer) {
				if( dto.owner() != null ) {
					consumer.accept(dto.owner());
				}
			}
		}
}
