// Generated by RSD - Do not modify
package at.bestsolution.quti.client;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;

import at.bestsolution.quti.client.dto.CalendarDTO;
import at.bestsolution.quti.client.dto.CalendarNewDTO;
import at.bestsolution.quti.client.dto.EventViewDTO;

public interface CalendarService extends BaseService {
    public String create(CalendarNewDTO calendar)
        throws InvalidContentException;

    public CalendarDTO get(String key)
        throws NotFoundException,
            InvalidArgumentException;

    public List<EventViewDTO> eventView(String key,LocalDate start,LocalDate end,ZoneId timezone)
        throws NotFoundException,
            InvalidArgumentException;

    public List<EventViewDTO> eventView(String key,LocalDate start,LocalDate end,ZoneId timezone,ZoneId resultTimeZone)
        throws NotFoundException,
            InvalidArgumentException;

}