// Generated by RSD - Do not modify
package at.bestsolution.quti.client;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;

import at.bestsolution.quti.client.model.Calendar;
import at.bestsolution.quti.client.model.CalendarNew;
import at.bestsolution.quti.client.model.EventView;

public interface CalendarService extends BaseService {
	public String create(CalendarNew.Data calendar)
			throws InvalidContentException;

	public Calendar.Data get(String key)
			throws NotFoundException,
			InvalidArgumentException;

	public void update(String key, Calendar.Patch changes)
			throws NotFoundException,
			InvalidArgumentException;

	public List<EventView.Data> eventView(String key, LocalDate start, LocalDate end, ZoneId timezone)
			throws NotFoundException,
			InvalidArgumentException;

	public List<EventView.Data> eventView(String key, LocalDate start, LocalDate end, ZoneId timezone,
			ZoneId resultTimeZone)
			throws NotFoundException,
			InvalidArgumentException;
}
