// Generated by RSD - Do not modify
package at.bestsolution.quti.client;

public class InvalidArgumentException extends RSDException {
	public InvalidArgumentException(String message) {
		super(Type.InvalidArgument, message);
	}
}
