// Generated by RSD - Do not modify
package at.bestsolution.quti.client;

public class InvalidContentException extends RuntimeException {
	public InvalidContentException(String message, Throwable t) {
		super(message, t);
	}
}
