/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Events, LocalDate } from "./components/multidayview/multidayview";
export { Events, LocalDate } from "./components/multidayview/multidayview";
export namespace Components {
    interface QutiMultidayview {
        "days": number;
        "events": Events | string;
        "hoursMax": number;
        "hoursMin": number;
        "startDate": LocalDate;
        "workingHoursMax": number;
        "workingHoursMin": number;
    }
}
declare global {
    interface HTMLQutiMultidayviewElement extends Components.QutiMultidayview, HTMLStencilElement {
    }
    var HTMLQutiMultidayviewElement: {
        prototype: HTMLQutiMultidayviewElement;
        new (): HTMLQutiMultidayviewElement;
    };
    interface HTMLElementTagNameMap {
        "quti-multidayview": HTMLQutiMultidayviewElement;
    }
}
declare namespace LocalJSX {
    interface QutiMultidayview {
        "days"?: number;
        "events"?: Events | string;
        "hoursMax"?: number;
        "hoursMin"?: number;
        "startDate"?: LocalDate;
        "workingHoursMax"?: number;
        "workingHoursMin"?: number;
    }
    interface IntrinsicElements {
        "quti-multidayview": QutiMultidayview;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "quti-multidayview": LocalJSX.QutiMultidayview & JSXBase.HTMLAttributes<HTMLQutiMultidayviewElement>;
        }
    }
}
