// Generated by RSD - Do not modify
package at.bestsolution.quti.rest.model;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.bestsolution.quti.service.model.Calendar;

public class CalendarDataImpl extends _BaseDataImpl implements Calendar.Data {
	CalendarDataImpl(JsonObject data) {
		super(data);
	}

	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	public String name() {
		return _JsonUtils.mapString(data, "name");
	}

	public String owner() {
		return _JsonUtils.mapString(data, "owner", null);
	}

	public static Calendar.Data of(JsonObject obj) {
		return new CalendarDataImpl(obj);
	}

	public String toString() {
		return "%s[%s=%s]".formatted(getClass().getSimpleName(), "key", key());
	}

	public static class DataBuilderImpl implements Calendar.DataBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public Calendar.DataBuilder key(String key) {
			$builder.add("key", key);
			return this;
		}

		public Calendar.DataBuilder name(String name) {
			if (name == null) {
				return this;
			}
			$builder.add("name", name);
			return this;
		}

		public Calendar.DataBuilder owner(String owner) {
			if (owner == null) {
				return this;
			}
			$builder.add("owner", owner);
			return this;
		}

		public Calendar.Data build() {
			return new CalendarDataImpl($builder.build());
		}
	}

	public static Calendar.DataBuilder builder() {
		return new DataBuilderImpl();
	}
}
