// Generated by RSD - Do not modify
package at.bestsolution.quti.rest.model;

import jakarta.json.JsonObject;

import at.bestsolution.quti.service.model.EventRepeat;

public abstract class EventRepeatDataImpl implements EventRepeat.Data {
    public static EventRepeat.Data of(JsonObject obj) {
        var descriminator = obj.getString("@type");
        return switch(descriminator) {
            case "daily" -> new EventRepeatDailyDataImpl(obj);
            case "weekly" -> new EventRepeatWeeklyDataImpl(obj);
            case "absolute-monthly" -> new EventRepeatAbsoluteMonthlyDataImpl(obj);
            case "absolute-yearly" -> new EventRepeatAbsoluteYearlyDataImpl(obj);
            case "relative-monthly" -> new EventRepeatRelativeMonthlyDataImpl(obj);
            case "relative-yearly" -> new EventRepeatRelativeYearlyDataImpl(obj);
            default -> throw new IllegalArgumentException("Unexpected value: %s".formatted(descriminator));
        };
    }
}