// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.client.jdkhttp.impl.model;

import java.util.Optional;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.bestsolution.quti.calendar.client.model._Base;
import at.bestsolution.quti.calendar.client.model.Calendar;

public class CalendarDataPatchImpl extends _BaseDataImpl implements Calendar.Patch {
	CalendarDataPatchImpl(JsonObject data) {
		super(data);
	}

	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	public Optional<String> name() {
		return _JsonUtils.mapOptString(data, "name");
	}

	public _Base.Nillable<String> owner() {
		return _JsonUtils.mapNilString(data, "owner");
	}

	public static class PatchBuilderImpl implements Calendar.PatchBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public Calendar.PatchBuilder key(String key) {
			$builder.add("key", key);
			return this;
		}

		@Override
		public Calendar.PatchBuilder name(String name) {
			$builder.add("name", name);
			return this;
		}

		@Override
		public Calendar.PatchBuilder owner(String owner) {
			if (owner == null) {
				$builder.addNull("owner");
				return this;
			}
			$builder.add("owner", owner);
			return this;
		}

		@Override
		public Calendar.Patch build() {
			return new CalendarDataPatchImpl($builder.build());
		}
	}

	public static Calendar.Patch of(JsonObject obj) {
		return new CalendarDataPatchImpl(obj);
	}

	public static PatchBuilderImpl builder() {
		return new PatchBuilderImpl();
	}
}
