// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.client.jdkhttp.impl.model;

import jakarta.json.JsonObject;

import at.bestsolution.quti.calendar.client.model.EventRepeat;

public abstract class EventRepeatPatchImpl implements EventRepeat.Patch {
	public static EventRepeat.Patch of(JsonObject obj) {
		var descriminator = obj.getString("@type");
		return switch (descriminator) {
			case "daily" -> new EventRepeatDailyDataPatchImpl(obj);
			case "weekly" -> new EventRepeatWeeklyDataPatchImpl(obj);
			case "absolute-monthly" -> new EventRepeatAbsoluteMonthlyDataPatchImpl(obj);
			case "absolute-yearly" -> new EventRepeatAbsoluteYearlyDataPatchImpl(obj);
			case "relative-monthly" -> new EventRepeatRelativeMonthlyDataPatchImpl(obj);
			case "relative-yearly" -> new EventRepeatRelativeYearlyDataPatchImpl(obj);
			default -> throw new IllegalArgumentException("Unexpected value: %s".formatted(descriminator));
		};
	}
}
