// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.client.jdkhttp.impl.model;

import jakarta.json.JsonObject;

import at.bestsolution.quti.calendar.client.model.EventRepeat;

public abstract class EventRepeatPatchImpl implements EventRepeat.Patch {
	public static boolean isSupportedType(JsonObject obj) {
		var descriminator = obj.getString("@type");
		return switch (descriminator) {
			case "patch:daily",
					"patch:weekly",
					"patch:absolute-monthly",
					"patch:absolute-yearly",
					"patch:relative-monthly",
					"patch:relative-yearly" ->
				true;
			default -> false;
		};
	}

	public static EventRepeat.Patch of(JsonObject obj) {
		var descriminator = obj.getString("@type");
		return switch (descriminator) {
			case "patch:daily" -> new EventRepeatDailyPatchImpl(obj);
			case "patch:weekly" -> new EventRepeatWeeklyPatchImpl(obj);
			case "patch:absolute-monthly" -> new EventRepeatAbsoluteMonthlyPatchImpl(obj);
			case "patch:absolute-yearly" -> new EventRepeatAbsoluteYearlyPatchImpl(obj);
			case "patch:relative-monthly" -> new EventRepeatRelativeMonthlyPatchImpl(obj);
			case "patch:relative-yearly" -> new EventRepeatRelativeYearlyPatchImpl(obj);
			default -> throw new IllegalArgumentException("Unexpected value: %s".formatted(descriminator));
		};
	}
}
