// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.client.jdkhttp.impl.model;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Optional;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.bestsolution.quti.calendar.client.model._Base;
import at.bestsolution.quti.calendar.client.model.EventRepeatAbsoluteMonthly;

public class EventRepeatAbsoluteMonthlyDataPatchImpl extends _BaseDataImpl implements EventRepeatAbsoluteMonthly.Patch {
	EventRepeatAbsoluteMonthlyDataPatchImpl(JsonObject data) {
		super(data);
	}

	public Optional<Short> dayOfMonth() {
		return _JsonUtils.mapOptShort(data, "dayOfMonth");
	}

	public Optional<Short> interval() {
		return _JsonUtils.mapOptShort(data, "interval");
	}

	public _Base.Nillable<LocalDate> endDate() {
		return _JsonUtils.mapNilLocalDate(data, "endDate");
	}

	public Optional<ZoneId> timeZone() {
		return _JsonUtils.mapOptLiteral(data, "timeZone", ZoneId::of);
	}

	public static class PatchBuilderImpl implements EventRepeatAbsoluteMonthly.PatchBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		@Override
		public EventRepeatAbsoluteMonthly.PatchBuilder dayOfMonth(short dayOfMonth) {
			$builder.add("dayOfMonth", dayOfMonth);
			return this;
		}

		@Override
		public EventRepeatAbsoluteMonthly.PatchBuilder interval(short interval) {
			$builder.add("interval", interval);
			return this;
		}

		@Override
		public EventRepeatAbsoluteMonthly.PatchBuilder endDate(LocalDate endDate) {
			if (endDate == null) {
				$builder.addNull("endDate");
				return this;
			}
			$builder.add("endDate", endDate.toString());
			return this;
		}

		@Override
		public EventRepeatAbsoluteMonthly.PatchBuilder timeZone(ZoneId timeZone) {
			$builder.add("timeZone", timeZone.toString());
			return this;
		}

		@Override
		public EventRepeatAbsoluteMonthly.Patch build() {
			return new EventRepeatAbsoluteMonthlyDataPatchImpl($builder.build());
		}
	}

	public static EventRepeatAbsoluteMonthly.Patch of(JsonObject obj) {
		return new EventRepeatAbsoluteMonthlyDataPatchImpl(obj);
	}

	public static PatchBuilderImpl builder() {
		return new PatchBuilderImpl();
	}
}
