// Generated by RSD - Do not modify
import { checkOptProp, checkProp, isRecord, isString, propValue } from '../_type-utils.ts';

export type CalendarNew = {
	readonly name: string;
	readonly owner?: string;
};

export function isCalendarNew(value: unknown): value is CalendarNew {
	return isRecord(value) &&
		checkProp(value, 'name', isString) &&
		checkOptProp(value, 'owner', isString);
}

export function CalendarNewFromJSON($value: Record<string, unknown>): CalendarNew {
	const name = propValue('name', $value, isString);
	const owner = propValue('owner', $value, isString, 'optional');
	return {
		name,
		owner,
	};
}

export function CalendarNewToJSON($value: CalendarNew): Record<string, unknown> {
	const name = $value.name;
	const owner = $value.owner;

	return {
		name,
		owner,
	};
}

