// Generated by RSD - Do not modify
export type DayOfWeek = 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY';

export function isDayOfWeek(value: unknown) {
	return value === 'MONDAY' || value === 'TUESDAY' || value === 'WEDNESDAY' || value === 'THURSDAY' || value === 'FRIDAY' || value === 'SATURDAY' || value === 'SUNDAY';
}
