// Generated by RSD - Do not modify
export type Month = 'JANUARY' | 'FEBRUARY' | 'MARCH' | 'APRIL' | 'MAY' | 'JUNE' | 'JULY' | 'AUGUST' | 'SEPTEMBER' | 'OCTOBER' | 'DECEMBER';

export function isMonth(value: unknown) {
	return value === 'JANUARY' || value === 'FEBRUARY' || value === 'MARCH' || value === 'APRIL' || value === 'MAY' || value === 'JUNE' || value === 'JULY' || value === 'AUGUST' || value === 'SEPTEMBER' || value === 'OCTOBER' || value === 'DECEMBER';
}
