// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.service.model;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Optional;

import at.bestsolution.quti.calendar.service.model.mixins.EventRepeatDataMixin;

public interface EventRepeatDaily {

	public interface Data extends _Base.BaseData, EventRepeatDaily, EventRepeatDataMixin, EventRepeat.Data {
		public short interval();

		public LocalDate endDate();

		public ZoneId timeZone();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<EventRepeatDaily.Data>, EventRepeat.DataBuilder {
		public DataBuilder interval(short interval);

		public DataBuilder endDate(LocalDate endDate);

		public DataBuilder timeZone(ZoneId timeZone);

	}

	public interface Patch extends _Base.BaseData, EventRepeatDaily {
		public Optional<Short> interval();

		public _Base.Nillable<LocalDate> endDate();

		public Optional<ZoneId> timeZone();

	}

	public interface PatchBuilder extends _Base.BaseDataBuilder<EventRepeatDaily.Patch> {
		public PatchBuilder interval(short interval);

		public PatchBuilder endDate(LocalDate endDate);

		public PatchBuilder timeZone(ZoneId timeZone);

	}
}
