// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.service.model;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Optional;

public interface EventRepeat {
	public interface Builder {

	}

	public interface Data extends EventRepeat {
		public short interval();

		public LocalDate endDate();

		public ZoneId timeZone();

	}

	public interface DataBuilder extends Builder {
	}

	public interface Patch extends EventRepeat {
		public Optional<Short> interval();



		public _Base.Nillable<LocalDate> endDate();



		public Optional<ZoneId> timeZone();



	}

	public interface PatchBuilder extends Builder {
	}

}
