// Generated by RSD - Do not modify
package at.bestsolution.quti.client.model.mixins;

import java.time.LocalDate;
import java.time.ZoneId;

public interface EventRepeatDataMixin {
	public short interval();

	public LocalDate endDate();

	public ZoneId timeZone();

}
