// Generated by RSD - Do not modify
package at.bestsolution.quti.rest;

import java.time.LocalDate;
import java.time.ZoneId;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.HeaderParam;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;

import at.bestsolution.quti.service.CalendarService;
import at.bestsolution.quti.service.model.Calendar;
import at.bestsolution.quti.service.model.CalendarNew;

@ApplicationScoped
@Path("/api/calendar")
@Produces(MediaType.APPLICATION_JSON)
public class CalendarResource {
	private final RestBuilderFactory builderFactory;
	private final CalendarService service;
	private final CalendarResourceResponseBuilder responseBuilder;

	@Inject
	public CalendarResource(CalendarService service, CalendarResourceResponseBuilder responseBuilder,
			RestBuilderFactory builderFactory) {
		this.builderFactory = builderFactory;
		this.service = service;
		this.responseBuilder = responseBuilder;
	}

	@POST
	public Response create(String _calendar) {
		var calendar = builderFactory.of(CalendarNew.Data.class, _calendar);
		var result = service.create(builderFactory, calendar);

		if (result.isOk()) {
			return responseBuilder.create(result.value(), calendar).build();
		}
		return RestUtils.toResponse(result);
	}

	@GET
	@Path("{key}")
	public Response get(@PathParam("key") String _key) {
		var key = _key;
		var result = service.get(builderFactory, key);

		if (result.isOk()) {
			return responseBuilder.get(result.value(), key).build();
		}
		return RestUtils.toResponse(result);
	}

	@PATCH
	@Path("{key}")
	public Response update(
			@PathParam("key") String _key,
			String _changes) {
		var key = _key;
		var changes = builderFactory.of(Calendar.Patch.class, _changes);
		var result = service.update(builderFactory, key, changes);

		if (result.isOk()) {
			return responseBuilder.update(key, changes).build();
		}
		return RestUtils.toResponse(result);
	}

	@GET
	@Path("{key}/view")
	public Response eventView(
			@PathParam("key") String _key,
			@QueryParam("from") LocalDate _start,
			@QueryParam("to") LocalDate _end,
			@QueryParam("timezone") String _timezone,
			@HeaderParam("timezone") String _resultTimeZone) {
		var key = _key;
		var start = _start;
		var end = _end;
		var timezone = _timezone == null ? null : ZoneId.of(_timezone);
		var resultTimeZone = _resultTimeZone == null ? null : ZoneId.of(_resultTimeZone);
		var result = service.eventView(builderFactory, key, start, end, timezone, resultTimeZone);

		if (result.isOk()) {
			return responseBuilder.eventView(result.value(), key, start, end, timezone, resultTimeZone).build();
		}
		return RestUtils.toResponse(result);
	}

}
