// Generated by RSD - Do not modify
package at.bestsolution.quti.rest;

import jakarta.inject.Singleton;

import at.bestsolution.quti.rest.dto.CalendarDTOImpl;
import at.bestsolution.quti.rest.dto.CalendarNewDTOImpl;
import at.bestsolution.quti.rest.dto.EventDTOImpl;
import at.bestsolution.quti.rest.dto.EventNewDTOImpl;
import at.bestsolution.quti.rest.dto.EventRepeatAbsoluteMonthlyDTOImpl;
import at.bestsolution.quti.rest.dto.EventRepeatAbsoluteYearlyDTOImpl;
import at.bestsolution.quti.rest.dto.EventRepeatDailyDTOImpl;
import at.bestsolution.quti.rest.dto.EventRepeatRelativeMonthlyDTOImpl;
import at.bestsolution.quti.rest.dto.EventRepeatRelativeYearlyDTOImpl;
import at.bestsolution.quti.rest.dto.EventRepeatWeeklyDTOImpl;
import at.bestsolution.quti.rest.dto.EventViewFilterDTOImpl;
import at.bestsolution.quti.rest.dto.SeriesEventViewDTOImpl;
import at.bestsolution.quti.rest.dto.SeriesMovedEventViewDTOImpl;
import at.bestsolution.quti.rest.dto.SingleEventViewDTOImpl;
import at.bestsolution.quti.service.dto.BaseDTO;
import at.bestsolution.quti.service.dto.CalendarDTO;
import at.bestsolution.quti.service.dto.CalendarNewDTO;
import at.bestsolution.quti.service.dto.EventDTO;
import at.bestsolution.quti.service.dto.EventNewDTO;
import at.bestsolution.quti.service.dto.EventRepeatAbsoluteMonthlyDTO;
import at.bestsolution.quti.service.dto.EventRepeatAbsoluteYearlyDTO;
import at.bestsolution.quti.service.dto.EventRepeatDailyDTO;
import at.bestsolution.quti.service.dto.EventRepeatRelativeMonthlyDTO;
import at.bestsolution.quti.service.dto.EventRepeatRelativeYearlyDTO;
import at.bestsolution.quti.service.dto.EventRepeatWeeklyDTO;
import at.bestsolution.quti.service.dto.EventViewFilterDTO;
import at.bestsolution.quti.service.dto.SeriesEventViewDTO;
import at.bestsolution.quti.service.dto.SeriesMovedEventViewDTO;
import at.bestsolution.quti.service.dto.SingleEventViewDTO;
import at.bestsolution.quti.service.DTOBuilderFactory;

@Singleton
public class RestDTOBuilderFactory implements DTOBuilderFactory {
    @Override
    public <T extends BaseDTO.Builder> T builder(Class<T> type) {
        if( type == CalendarDTO.Builder.class) {
            return type.cast(CalendarDTOImpl.builder());
        }
        if( type == CalendarNewDTO.Builder.class) {
            return type.cast(CalendarNewDTOImpl.builder());
        }
        if( type == EventNewDTO.Builder.class) {
            return type.cast(EventNewDTOImpl.builder());
        }
        if( type == EventDTO.Builder.class) {
            return type.cast(EventDTOImpl.builder());
        }
        if( type == EventViewFilterDTO.Builder.class) {
            return type.cast(EventViewFilterDTOImpl.builder());
        }
        if( type == EventRepeatDailyDTO.Builder.class) {
            return type.cast(EventRepeatDailyDTOImpl.builder());
        }
        if( type == EventRepeatWeeklyDTO.Builder.class) {
            return type.cast(EventRepeatWeeklyDTOImpl.builder());
        }
        if( type == EventRepeatAbsoluteMonthlyDTO.Builder.class) {
            return type.cast(EventRepeatAbsoluteMonthlyDTOImpl.builder());
        }
        if( type == EventRepeatAbsoluteYearlyDTO.Builder.class) {
            return type.cast(EventRepeatAbsoluteYearlyDTOImpl.builder());
        }
        if( type == EventRepeatRelativeMonthlyDTO.Builder.class) {
            return type.cast(EventRepeatRelativeMonthlyDTOImpl.builder());
        }
        if( type == EventRepeatRelativeYearlyDTO.Builder.class) {
            return type.cast(EventRepeatRelativeYearlyDTOImpl.builder());
        }
        if( type == SingleEventViewDTO.Builder.class) {
            return type.cast(SingleEventViewDTOImpl.builder());
        }
        if( type == SeriesMovedEventViewDTO.Builder.class) {
            return type.cast(SeriesMovedEventViewDTOImpl.builder());
        }
        if( type == SeriesEventViewDTO.Builder.class) {
            return type.cast(SeriesEventViewDTOImpl.builder());
        }
        throw new IllegalArgumentException("Unsupported Builder '%s'".formatted(type));
    }
}
