// Generated by RSD - Do not modify
package at.bestsolution.quti.client.jdkhttp.impl.dto;

import java.util.List;

import jakarta.json.Json;
import jakarta.json.JsonArray;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.bestsolution.quti.client.dto.CalendarDTO;

public class CalendarDTOImpl extends BaseDTOImpl implements CalendarDTO {

    CalendarDTOImpl(JsonObject data) {
        super(data);
    }

    @Override
    public String key() {
        return DTOUtils.mapString(data, "key");
    }

    @Override
    public String name() {
        return DTOUtils.mapString(data, "name");
    }

    @Override
    public String owner() {
        return DTOUtils.mapString(data, "owner");
    }

    public static CalendarDTO of(JsonObject data) {
        return new CalendarDTOImpl(data);
    }

    public static List<CalendarDTO> of(JsonArray data) {
        return DTOUtils.mapObjects(data, CalendarDTOImpl::of);
    }

    @Override
    public String toString() {
        return "%s[%s=%s]".formatted(getClass().getSimpleName(), "key", key());
    }

    public static class BuilderImpl implements Builder {
        private JsonObjectBuilder $builder = Json.createObjectBuilder();

        @Override
        public Builder key(String key) {
            $builder.add("key", key);
            return this;
        }

        @Override
        public Builder name(String name) {
            $builder.add("name", name);
            return this;
        }

        @Override
        public Builder owner(String owner) {
            $builder.add("owner", owner);
            return this;
        }

        public CalendarDTO build() {
            return new CalendarDTOImpl($builder.build());
        }
    }
}
