// Generated by RSD - Do not modify
package at.bestsolution.quti.client.jdkhttp.impl.dto;

import java.util.List;

import jakarta.json.Json;
import jakarta.json.JsonArray;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import at.bestsolution.quti.client.dto.CalendarNewDTO;

public class CalendarNewDTOImpl extends BaseDTOImpl implements CalendarNewDTO {

    CalendarNewDTOImpl(JsonObject data) {
        super(data);
    }

    @Override
    public String name() {
        return DTOUtils.mapString(data, "name");
    }

    @Override
    public String owner() {
        return DTOUtils.mapString(data, "owner");
    }

    public static CalendarNewDTO of(JsonObject data) {
        return new CalendarNewDTOImpl(data);
    }

    public static List<CalendarNewDTO> of(JsonArray data) {
        return DTOUtils.mapObjects(data, CalendarNewDTOImpl::of);
    }

    public static class BuilderImpl implements Builder {
        private JsonObjectBuilder $builder = Json.createObjectBuilder();

        @Override
        public Builder name(String name) {
            $builder.add("name", name);
            return this;
        }

        @Override
        public Builder owner(String owner) {
            $builder.add("owner", owner);
            return this;
        }

        public CalendarNewDTO build() {
            return new CalendarNewDTOImpl($builder.build());
        }
    }
}
