// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.client;

public class InvalidContentException extends RSDException {
	public InvalidContentException(String message) {
		super(Type.InvalidContent, message);
	}
}
