// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.client;

import java.net.URI;
import java.util.ServiceLoader;

import at.bestsolution.quti.calendar.client.model._Base;
import at.bestsolution.quti.calendar.client.spi.QutiClientFactory;

public interface QutiClient {
	public static QutiClient create(URI baseURL) {
		return ServiceLoader.load(QutiClientFactory.class).iterator().next().create(baseURL);
	}

	public <T extends _Base.BaseDataBuilder<?>> T builder(Class<T> clazz);

	public <T extends BaseService> T service(Class<T> clazz);
}
