// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.client.model;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Optional;

public interface EventRepeat {
	public interface Builder {

	}

	public interface Data extends _Base.BaseData, EventRepeat {
		public short interval();

		public LocalDate endDate();

		public ZoneId timeZone();

	}

	public interface DataBuilder extends Builder {
	}

	public interface Patch extends _Base.BaseData, EventRepeat {
		public Optional<Short> interval();

		public _Base.Nillable<LocalDate> endDate();

		public Optional<ZoneId> timeZone();

	}

	public interface PatchBuilder extends Builder {
	}

}
