// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.client.model;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.Month;
import java.time.ZoneId;
import java.util.List;
import java.util.Optional;

import at.bestsolution.quti.calendar.client.model.mixins.EventRepeatDataMixin;

public interface EventRepeatRelativeYearly {

	public interface Data extends _Base.BaseData, EventRepeatRelativeYearly, EventRepeatDataMixin, EventRepeat.Data {
		public List<DayOfWeek> daysOfWeek();

		public Month month();

		public short interval();

		public LocalDate endDate();

		public ZoneId timeZone();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<EventRepeatRelativeYearly.Data>, EventRepeat.DataBuilder {
		public DataBuilder daysOfWeek(List<DayOfWeek> daysOfWeek);

		public DataBuilder month(Month month);

		public DataBuilder interval(short interval);

		public DataBuilder endDate(LocalDate endDate);

		public DataBuilder timeZone(ZoneId timeZone);

	}

	public interface Patch extends _Base.BaseData, EventRepeatRelativeYearly {
		public Optional<_Base.ListChange<_Base.ListSetElementsChange<DayOfWeek>, _Base.ListAddRemoveChange<DayOfWeek, DayOfWeek>>> daysOfWeek();

		public Optional<Month> month();

		public Optional<Short> interval();

		public _Base.Nillable<LocalDate> endDate();

		public Optional<ZoneId> timeZone();

	}

	public interface PatchBuilder extends _Base.BaseDataBuilder<EventRepeatRelativeYearly.Patch> {
		public PatchBuilder daysOfWeek(_Base.ListChange<_Base.ListSetElementsChange<DayOfWeek>, _Base.ListAddRemoveChange<DayOfWeek, DayOfWeek>> daysOfWeek);

		public PatchBuilder daysOfWeek(List<DayOfWeek> additions, List<DayOfWeek> removals);
		public PatchBuilder daysOfWeek(List<DayOfWeek> elements);

		public PatchBuilder month(Month month);

		public PatchBuilder interval(short interval);

		public PatchBuilder endDate(LocalDate endDate);

		public PatchBuilder timeZone(ZoneId timeZone);

	}
}
