// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.client.model;

import java.time.ZonedDateTime;
import java.util.function.Function;
import java.util.List;
import java.util.Optional;

import at.bestsolution.quti.calendar.client.model.mixins.EventDataMixin;

public interface Event {

	public interface Data extends _Base.BaseData, Event, EventDataMixin {
		public String key();

		public String title();

		public String description();

		public ZonedDateTime start();

		public ZonedDateTime end();

		public boolean fullday();

		public EventRepeat.Data repeat();

		public List<String> tags();

		public List<String> referencedCalendars();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<Event.Data> {
		public DataBuilder key(String key);

		public DataBuilder title(String title);

		public DataBuilder description(String description);

		public DataBuilder start(ZonedDateTime start);

		public DataBuilder end(ZonedDateTime end);

		public DataBuilder fullday(boolean fullday);

		public DataBuilder repeat(EventRepeat.Data repeat);

		public <T extends EventRepeat.DataBuilder> DataBuilder withRepeat(Class<T> clazz,
				Function<T, EventRepeat.Data> block);

		public DataBuilder tags(List<String> tags);

		public DataBuilder referencedCalendars(List<String> referencedCalendars);

	}

	public interface Patch extends _Base.BaseData, Event {
		public interface TagsChange {

		}

		public interface TagsSetChange extends TagsChange, _Base.ListSetElementsChange<String> {
		}

		public interface TagsAddRemoveChange extends TagsChange, _Base.ListAddRemoveChange<String, String> {
		}

		public String key();

		public Optional<String> title();

		public _Base.Nillable<String> description();

		public Optional<ZonedDateTime> start();

		public Optional<ZonedDateTime> end();

		public _Base.Nillable<Boolean> fullday();

		public _Base.Nillable<at.bestsolution.quti.calendar.client.model.EventRepeat> repeat();

		// public Optional<_Base.ListChange<_Base.ListSetElementsChange<String>,
		// _Base.ListAddRemoveChange<String, String>>> tags();

		public Optional<TagsChange> tags();

		public Optional<_Base.ListChange<_Base.ListSetElementsChange<String>, _Base.ListAddRemoveChange<String, String>>> referencedCalendars();

	}

	public interface PatchBuilder extends _Base.BaseDataBuilder<Event.Patch> {
		public PatchBuilder key(String key);

		public PatchBuilder title(String title);

		public PatchBuilder description(String description);

		public PatchBuilder start(ZonedDateTime start);

		public PatchBuilder end(ZonedDateTime end);

		public PatchBuilder fullday(Boolean fullday);

		public PatchBuilder repeat(EventRepeat repeat);

		public <T extends EventRepeat.Builder> PatchBuilder withRepeat(Class<T> clazz, Function<T, EventRepeat> block);

		public PatchBuilder tags(
				_Base.ListChange<_Base.ListSetElementsChange<String>, _Base.ListAddRemoveChange<String, String>> tags);

		public PatchBuilder tags(List<String> additions, List<String> removals);

		public PatchBuilder tags(List<String> elements);

		public PatchBuilder referencedCalendars(
				_Base.ListChange<_Base.ListSetElementsChange<String>, _Base.ListAddRemoveChange<String, String>> referencedCalendars);

		public PatchBuilder referencedCalendars(List<String> additions, List<String> removals);

		public PatchBuilder referencedCalendars(List<String> elements);

	}
}
