// Generated by RSD - Do not modify
import { ifDefined, safeExecute, ServiceProps } from './_fetch-type-utils.ts';
import { api } from '../index.ts';

export function createEventService(props: ServiceProps<api.service.ErrorType>): api.service.EventService {
	return {
		create: fnCreate(props),
		get: fnGet(props),
		search: fnSearch(props),
		update: fnUpdate(props),
		delete: fnDelete(props),
		cancel: fnCancel(props),
		uncancel: fnUncancel(props),
		move: fnMove(props),
		endRepeat: fnEndRepeat(props),
		description: fnDescription(props),
	};
}
function fnCreate(props: ServiceProps<api.service.ErrorType>): api.service.EventService['create'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onError, onCatch, final } = lifecycleHandlers;
	return async (calendar: string, event: api.model.EventNew) => {
		try {
			const $init = (await preFetch?.('create')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			$init.headers = $headers;

			const $path = `${baseUrl}/api/calendar/${calendar}/events/`;
			const $body = JSON.stringify(api.model.EventNewToJSON(event));
			const $response = await fetchAPI($path, { ...$init, method: 'POST', body: $body });
			if($response.status === 201) {
				const $data = await $response.json();
				return safeExecute(api.result.OK($data), () => onSuccess?.('create', $data));
			} else if($response.status === 404) {
				const err = {
					_type: 'NotFound',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('create', err));
			} else if($response.status === 400) {
				const err = {
					_type: 'InvalidArgument',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('create', err));
			}
			const err = { _type: '_Status', message: $response.statusText, status: $response.status, } as const;
			return api.result.ERR(err);
		} catch(e) {
			onCatch?.('create', e)
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee, } as const;
			return api.result.ERR(err);
		} finally {
			final?.('create');
		}
	};
}

function fnGet(props: ServiceProps<api.service.ErrorType>): api.service.EventService['get'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onError, onCatch, final } = lifecycleHandlers;
	return async (calendar: string, key: string, timezone: string) => {
		try {
			const $init = (await preFetch?.('get')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			$headers.append('timezone',`${timezone}`);
			$init.headers = $headers;

			const $path = `${baseUrl}/api/calendar/${calendar}/events/${key}`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if($response.status === 200) {
				const $data = await $response.json();
				const $result = api.model.EventFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('get', $result));
			} else if($response.status === 404) {
				const err = {
					_type: 'NotFound',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('get', err));
			} else if($response.status === 400) {
				const err = {
					_type: 'InvalidArgument',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('get', err));
			}
			const err = { _type: '_Status', message: $response.statusText, status: $response.status, } as const;
			return api.result.ERR(err);
		} catch(e) {
			onCatch?.('get', e)
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee, } as const;
			return api.result.ERR(err);
		} finally {
			final?.('get');
		}
	};
}

function fnSearch(props: ServiceProps<api.service.ErrorType>): api.service.EventService['search'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onError, onCatch, final } = lifecycleHandlers;
	return async (calendar: string, filter: api.model.EventSearch, timezone?: string) => {
		try {
			const $init = (await preFetch?.('search')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			ifDefined(timezone, v => $headers.append('timezone',`${v}`));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/calendar/${calendar}/events/search`;
			const $body = JSON.stringify(api.model.EventSearchToJSON(filter));
			const $response = await fetchAPI($path, { ...$init, method: 'PUT', body: $body });
			if($response.status === 200) {
				const $data = await $response.json();
				if(!api.utils.isArray) {
					throw new Error('Invalid result');
				}
				const $result = $data.map(api.model.EventFromJSON);
				return safeExecute(api.result.OK($result), () => onSuccess?.('search', $result));
			} else if($response.status === 400) {
				const err = {
					_type: 'InvalidArgument',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('search', err));
			}
			const err = { _type: '_Status', message: $response.statusText, status: $response.status, } as const;
			return api.result.ERR(err);
		} catch(e) {
			onCatch?.('search', e)
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee, } as const;
			return api.result.ERR(err);
		} finally {
			final?.('search');
		}
	};
}

function fnUpdate(props: ServiceProps<api.service.ErrorType>): api.service.EventService['update'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onError, onCatch, final } = lifecycleHandlers;
	return async (calendar: string, key: string, changes: api.model.Event) => {
		try {
			const $init = (await preFetch?.('update')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			$init.headers = $headers;

			const $path = `${baseUrl}/api/calendar/${calendar}/events/${key}`;
			const $body = JSON.stringify(api.model.EventPatchToJSON(changes));
			const $response = await fetchAPI($path, { ...$init, method: 'PATCH', body: $body });
			if($response.status === 204) {
				return safeExecute(api.result.OK(api.result.Void), () => onSuccess?.('update', api.result.Void));
			} else if($response.status === 404) {
				const err = {
					_type: 'NotFound',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('update', err));
			} else if($response.status === 400) {
				const err = {
					_type: 'InvalidArgument',
					message: await $response.text(),
				} as const;
				return safeExecute(api.result.ERR(err), () => onError?.('update', err));
			}
			const err = { _type: '_Status', message: $response.statusText, status: $response.status, } as const;
			return api.result.ERR(err);
		} catch(e) {
			onCatch?.('update', e)
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee, } as const;
			return api.result.ERR(err);
		} finally {
			final?.('update');
		}
	};
}

function fnDelete(props: ServiceProps<api.service.ErrorType>): api.service.EventService['delete'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (calendar: string, key: string) => {
		try {
			const $init = (await preFetch?.('delete')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			$init.headers = $headers;

			const $path = `${baseUrl}/api/calendar/${calendar}/events/${key}`;
			const $response = await fetchAPI($path, { ...$init, method: 'DELETE' });

			if ($response.status == 204) {
				return safeExecute(api.result.OK(api.result.Void), () => onSuccess?.('delete', api.result.Void));
			}
			const err = { _type: '_Status', message: $response.statusText, status: $response.status, } as const;
			return api.result.ERR(err);
		} catch(e) {
			onCatch?.('delete', e)
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee, } as const;
			return api.result.ERR(err);
		} finally {
			final?.('delete');
		}
	};
}

function fnCancel(props: ServiceProps<api.service.ErrorType>): api.service.EventService['cancel'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (calendar: string, key: string) => {
		try {
			const $init = (await preFetch?.('cancel')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			$init.headers = $headers;

			const $path = `${baseUrl}/api/calendar/${calendar}/events/${key}/action/cancel`;
			const $response = await fetchAPI($path, { ...$init, method: 'PUT' });

			if ($response.status == 204) {
				return safeExecute(api.result.OK(api.result.Void), () => onSuccess?.('cancel', api.result.Void));
			}
			const err = { _type: '_Status', message: $response.statusText, status: $response.status, } as const;
			return api.result.ERR(err);
		} catch(e) {
			onCatch?.('cancel', e)
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee, } as const;
			return api.result.ERR(err);
		} finally {
			final?.('cancel');
		}
	};
}

function fnUncancel(props: ServiceProps<api.service.ErrorType>): api.service.EventService['uncancel'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (calendar: string, key: string) => {
		try {
			const $init = (await preFetch?.('uncancel')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			$init.headers = $headers;

			const $path = `${baseUrl}/api/calendar/${calendar}/events/${key}/action/uncancel`;
			const $response = await fetchAPI($path, { ...$init, method: 'PUT' });

			if ($response.status == 204) {
				return safeExecute(api.result.OK(api.result.Void), () => onSuccess?.('uncancel', api.result.Void));
			}
			const err = { _type: '_Status', message: $response.statusText, status: $response.status, } as const;
			return api.result.ERR(err);
		} catch(e) {
			onCatch?.('uncancel', e)
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee, } as const;
			return api.result.ERR(err);
		} finally {
			final?.('uncancel');
		}
	};
}

function fnMove(props: ServiceProps<api.service.ErrorType>): api.service.EventService['move'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (calendar: string, key: string, start: string, end: string) => {
		try {
			const $init = (await preFetch?.('move')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			$init.headers = $headers;

			const $path = `${baseUrl}/api/calendar/${calendar}/events/${key}/action/move`;
			const $body = JSON.stringify({
				start: `${start}`,
				end: `${end}`,
			});
			const $response = await fetchAPI($path, { ...$init, method: 'PUT', body: $body });
			if ($response.status == 204) {
				return safeExecute(api.result.OK(api.result.Void), () => onSuccess?.('move', api.result.Void));
			}
			const err = { _type: '_Status', message: $response.statusText, status: $response.status, } as const;
			return api.result.ERR(err);
		} catch(e) {
			onCatch?.('move', e)
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee, } as const;
			return api.result.ERR(err);
		} finally {
			final?.('move');
		}
	};
}

function fnEndRepeat(props: ServiceProps<api.service.ErrorType>): api.service.EventService['endRepeat'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (calendar: string, key: string, end: string) => {
		try {
			const $init = (await preFetch?.('endRepeat')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			$init.headers = $headers;

			const $path = `${baseUrl}/api/calendar/${calendar}/events/${key}/action/end-repeat`;
			const $body = `${end}`;
			const $response = await fetchAPI($path, { ...$init, method: 'PUT', body: $body });
			if ($response.status == 204) {
				return safeExecute(api.result.OK(api.result.Void), () => onSuccess?.('endRepeat', api.result.Void));
			}
			const err = { _type: '_Status', message: $response.statusText, status: $response.status, } as const;
			return api.result.ERR(err);
		} catch(e) {
			onCatch?.('endRepeat', e)
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee, } as const;
			return api.result.ERR(err);
		} finally {
			final?.('endRepeat');
		}
	};
}

function fnDescription(props: ServiceProps<api.service.ErrorType>): api.service.EventService['description'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (calendar: string, key: string, description: string) => {
		try {
			const $init = (await preFetch?.('description')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Content-Type', 'application/json');
			$init.headers = $headers;

			const $path = `${baseUrl}/api/calendar/${calendar}/events/${key}/action/description`;
			const $body = `${description}`;
			const $response = await fetchAPI($path, { ...$init, method: 'PUT', body: $body });
			if ($response.status == 204) {
				return safeExecute(api.result.OK(api.result.Void), () => onSuccess?.('description', api.result.Void));
			}
			const err = { _type: '_Status', message: $response.statusText, status: $response.status, } as const;
			return api.result.ERR(err);
		} catch(e) {
			onCatch?.('description', e)
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee, } as const;
			return api.result.ERR(err);
		} finally {
			final?.('description');
		}
	};
}

