// Generated by RSD - Do not modify
package at.bestsolution.quti.rest.dto;

public record CalendarDTOImpl(
    String key,
    String name,
    String owner) implements at.bestsolution.quti.service.dto.CalendarDTO {
}
