// Generated by RSD - Do not modify
package at.bestsolution.quti.rest.dto;

import at.bestsolution.quti.service.dto.CalendarNewDTO;

public record CalendarNewDTOImpl(
    String name,
    String owner) implements CalendarNewDTO {

    public static CalendarNewDTOImpl of(CalendarNewDTO source) {
        if(source == null) {
            return null;
        }
        else if(source instanceof CalendarNewDTOImpl) {
            return (CalendarNewDTOImpl)source;
        }
        return new CalendarNewDTOImpl(
            source.name(),
            source.owner()
        );
    }
    public static class BuilderImpl implements Builder {
        String name;
        String owner;

        public Builder name(String name) {
            this.name = name;
            return this;
        }
        public Builder owner(String owner) {
            this.owner = owner;
            return this;
        }

        public at.bestsolution.quti.service.dto.CalendarNewDTO build() {
            return new CalendarNewDTOImpl(name, owner);
        }
    }

    public static Builder builder() {
        return new BuilderImpl();
    }
}