// Generated by RSD - Do not modify
package at.bestsolution.quti.rest.dto;

public record CalendarNewDTO(
    String name,
    String owner) implements at.bestsolution.quti.service.dto.CalendarNewDTO {
}