// Generated by RSD - Do not modify
package at.bestsolution.quti.rest.dto;

import java.time.ZonedDateTime;
import java.util.List;

import jakarta.json.bind.annotation.JsonbSubtype;
import jakarta.json.bind.annotation.JsonbTypeInfo;

@JsonbTypeInfo({
    @JsonbSubtype(alias = "single", type = EventViewDTOImpl.SingleEventViewDTOImpl.class),
    @JsonbSubtype(alias = "series-moved", type = EventViewDTOImpl.SeriesMovedEventViewDTOImpl.class),
    @JsonbSubtype(alias = "series", type = EventViewDTOImpl.SeriesEventViewDTOImpl.class),
})
public abstract class EventViewDTOImpl implements at.bestsolution.quti.service.dto.EventViewDTO {
    public String key;
    public String calendarKey;
    public String title;
    public String description;
    public String owner;
    public Status status;
    public ZonedDateTime start;
    public ZonedDateTime end;
    public List<String> tags;
    public List<String> referencedCalendars;

    public String key() {
        return this.key;
    }

    public String calendarKey() {
        return this.calendarKey;
    }

    public String title() {
        return this.title;
    }

    public String description() {
        return this.description;
    }

    public String owner() {
        return this.owner;
    }

    public Status status() {
        return this.status;
    }

    public ZonedDateTime start() {
        return this.start;
    }

    public ZonedDateTime end() {
        return this.end;
    }

    public List<String> tags() {
        return this.tags;
    }

    public List<String> referencedCalendars() {
        return this.referencedCalendars;
    }

    public static class SingleEventViewDTOImpl extends EventViewDTOImpl implements at.bestsolution.quti.service.dto.EventViewDTO.SingleEventViewDTO {
    }

    public static class SeriesMovedEventViewDTOImpl extends EventViewDTOImpl implements at.bestsolution.quti.service.dto.EventViewDTO.SeriesMovedEventViewDTO {
        public String masterEventKey;
        public ZonedDateTime originalStart;
        public ZonedDateTime originalEnd;

        public String masterEventKey() {
            return this.masterEventKey;
        }

        public ZonedDateTime originalStart() {
            return this.originalStart;
        }

        public ZonedDateTime originalEnd() {
            return this.originalEnd;
        }
    }

    public static class SeriesEventViewDTOImpl extends EventViewDTOImpl implements at.bestsolution.quti.service.dto.EventViewDTO.SeriesEventViewDTO {
        public String masterEventKey;

        public String masterEventKey() {
            return this.masterEventKey;
        }
    }
}
