// Generated by RSD - Do not modify
package at.bestsolution.quti.rest.dto;

import java.time.ZonedDateTime;
import java.util.List;

import jakarta.json.bind.annotation.JsonbSubtype;
import jakarta.json.bind.annotation.JsonbTypeInfo;

import at.bestsolution.quti.service.dto.MixinEventViewDataDTO.Status;
import at.bestsolution.quti.service.dto.SeriesEventViewDTO;
import at.bestsolution.quti.service.dto.SeriesMovedEventViewDTO;
import at.bestsolution.quti.service.dto.SingleEventViewDTO;

@JsonbTypeInfo({
		@JsonbSubtype(alias = "single", type = SingleEventViewDTOImpl.class),
		@JsonbSubtype(alias = "series-moved", type = SeriesMovedEventViewDTOImpl.class),
		@JsonbSubtype(alias = "series", type = SeriesEventViewDTOImpl.class),
})
public abstract class EventViewDTOImpl implements at.bestsolution.quti.service.dto.EventViewDTO {
	public String key;
	public String calendarKey;
	public String title;
	public String description;
	public String owner;
	public Status status;
	public ZonedDateTime start;
	public ZonedDateTime end;
	public List<String> tags;
	public List<String> referencedCalendars;

	public EventViewDTOImpl() {
	}

	public EventViewDTOImpl(
			String key,
			String calendarKey,
			String title,
			String description,
			String owner,
			Status status,
			ZonedDateTime start,
			ZonedDateTime end,
			List<String> tags,
			List<String> referencedCalendars) {
		this.key = key;
		this.calendarKey = calendarKey;
		this.title = title;
		this.description = description;
		this.owner = owner;
		this.status = status;
		this.start = start;
		this.end = end;
		this.tags = tags;
		this.referencedCalendars = referencedCalendars;
	}

	public String key() {
		return this.key;
	}

	public String calendarKey() {
		return this.calendarKey;
	}

	public String title() {
		return this.title;
	}

	public String description() {
		return this.description;
	}

	public String owner() {
		return this.owner;
	}

	public Status status() {
		return this.status;
	}

	public ZonedDateTime start() {
		return this.start;
	}

	public ZonedDateTime end() {
		return this.end;
	}

	public List<String> tags() {
		return this.tags;
	}

	public List<String> referencedCalendars() {
		return this.referencedCalendars;
	}

	public static EventViewDTOImpl of(at.bestsolution.quti.service.dto.EventViewDTO source) {
		if (source == null) {
			return null;
		} else if (source instanceof EventViewDTOImpl) {
			return (EventViewDTOImpl) source;
		}
		if (source instanceof SingleEventViewDTO t) {
			return SingleEventViewDTOImpl.of(t);
		}
		if (source instanceof SeriesMovedEventViewDTO t) {
			return SeriesMovedEventViewDTOImpl.of(t);
		}
		if (source instanceof SeriesEventViewDTO t) {
			return SeriesEventViewDTOImpl.of(t);
		}
		throw new IllegalStateException("Unsupported type '%s'".formatted(source));
	}

	public static abstract class BuilderImpl implements Builder {
		String key;
		String calendarKey;
		String title;
		String description;
		String owner;
		Status status;
		ZonedDateTime start;
		ZonedDateTime end;
		List<String> tags;
		List<String> referencedCalendars;

		public Builder key(String key) {
			this.key = key;
			return this;
		}

		public Builder calendarKey(String calendarKey) {
			this.calendarKey = calendarKey;
			return this;
		}

		public Builder title(String title) {
			this.title = title;
			return this;
		}

		public Builder description(String description) {
			this.description = description;
			return this;
		}

		public Builder owner(String owner) {
			this.owner = owner;
			return this;
		}

		public Builder status(Status status) {
			this.status = status;
			return this;
		}

		public Builder start(ZonedDateTime start) {
			this.start = start;
			return this;
		}

		public Builder end(ZonedDateTime end) {
			this.end = end;
			return this;
		}

		public Builder tags(List<String> tags) {
			this.tags = tags;
			return this;
		}

		public Builder referencedCalendars(List<String> referencedCalendars) {
			this.referencedCalendars = referencedCalendars;
			return this;
		}
	}
}
