// Generated by RSD - Do not modify
package at.bestsolution.quti.rest.dto;

import java.util.List;

public record EventViewFilterDTOImpl(
    String owner,
    String title,
    String description,
    boolean fullday,
    List<String> tags) implements at.bestsolution.quti.service.dto.EventViewFilterDTO {

    public static EventViewFilterDTOImpl of(at.bestsolution.quti.service.dto.EventViewFilterDTO source) {
        if(source instanceof EventViewFilterDTOImpl) {
            return (EventViewFilterDTOImpl)source;
        }
        return new EventViewFilterDTOImpl(
            source.owner(),
            source.title(),
            source.description(),
            source.fullday(),
            source.tags()
        );
    }}