// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.rest.model;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.Optional;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;
import jakarta.json.JsonString;

import at.bestsolution.quti.calendar.service.model._Base;
import at.bestsolution.quti.calendar.service.model.EventRepeatRelativeMonthly;

public class EventRepeatRelativeMonthlyDataPatchImpl extends _BaseDataImpl implements EventRepeatRelativeMonthly.Patch {
	static class DaysOfWeekSetChangeImpl extends _ListChangeSupport.ValueElementsChange<DayOfWeek> implements DaysOfWeekSetChange {
		DaysOfWeekSetChangeImpl(JsonObject data) {
			super(data, v -> DayOfWeek.valueOf(((JsonString)v).getString()));
		}
	}

	static class DaysOfWeekMergeChangeImpl extends _ListChangeSupport.AddRemoveListChangeImpl<DayOfWeek, DayOfWeek> implements DaysOfWeekMergeChange {
		DaysOfWeekMergeChangeImpl(JsonObject data) {
			super(data, v -> DayOfWeek.valueOf(((JsonString)v).getString()), v -> DayOfWeek.valueOf(((JsonString)v).getString()));
		}
	}

	EventRepeatRelativeMonthlyDataPatchImpl(JsonObject data) {
		super(data);
	}

	public Optional<DaysOfWeekChange> daysOfWeek() {
		return _JsonUtils.mapOptObject(data, "daysOfWeek", o -> _ListChangeSupport.of(o, "@type", DaysOfWeekSetChangeImpl::new, DaysOfWeekMergeChangeImpl::new));
	}

	public Optional<Short> interval() {
		return _JsonUtils.mapOptShort(data, "interval");
	}

	public _Base.Nillable<LocalDate> endDate() {
		return _JsonUtils.mapNilLocalDate(data, "endDate");
	}

	public Optional<ZoneId> timeZone() {
		return _JsonUtils.mapOptLiteral(data, "timeZone", ZoneId::of);
	}

	public static class PatchBuilderImpl implements EventRepeatRelativeMonthly.PatchBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public PatchBuilderImpl() {
			$builder.add("@type", "patch:relative-monthly");
		}

		@Override
		public EventRepeatRelativeMonthly.PatchBuilder daysOfWeek(DaysOfWeekChange daysOfWeek) {
			$builder.add("daysOfWeek", ((_BaseDataImpl) daysOfWeek).data);
			return this;
		}

		public EventRepeatRelativeMonthly.PatchBuilder daysOfWeek(List<DayOfWeek> additions, List<DayOfWeek> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge-change");
			$changeBuilder.add("additions", _JsonUtils.toJsonLiteralArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonLiteralArray(removals));
			$builder.add("daysOfWeek", $changeBuilder.build());
			return this;
		}

		public EventRepeatRelativeMonthly.PatchBuilder daysOfWeek(List<DayOfWeek> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "set-change");
			$changeBuilder.add("elements", _JsonUtils.toJsonLiteralArray(elements));
			$builder.add("daysOfWeek", $changeBuilder.build());
			return this;
		}

		@Override
		public EventRepeatRelativeMonthly.PatchBuilder interval(short interval) {
			$builder.add("interval", interval);
			return this;
		}

		@Override
		public EventRepeatRelativeMonthly.PatchBuilder endDate(LocalDate endDate) {
			if (endDate == null) {
				$builder.addNull("endDate");
				return this;
			}
			$builder.add("endDate", endDate.toString());
			return this;
		}

		@Override
		public EventRepeatRelativeMonthly.PatchBuilder timeZone(ZoneId timeZone) {
			$builder.add("timeZone", timeZone.toString());
			return this;
		}

		@Override
		public EventRepeatRelativeMonthly.Patch build() {
			return new EventRepeatRelativeMonthlyDataPatchImpl($builder.build());
		}
	}

	public static EventRepeatRelativeMonthly.Patch of(JsonObject obj) {
		return new EventRepeatRelativeMonthlyDataPatchImpl(obj);
	}

	public static PatchBuilderImpl builder() {
		return new PatchBuilderImpl();
	}
}
