// Generated by RSD - Do not modify
package at.bestsolution.quti.calendar.client.spi;

import java.net.URI;

import at.bestsolution.quti.calendar.client.QutiClient;

public interface QutiClientFactory {
	public QutiClient create(URI uri);
}
