// Generated by RSD - Do not modify
package at.bestsolution.quti.client.model;

import java.util.function.Consumer;
import java.util.function.Function;

public interface _Base {

	public interface Nillable<T> {
		public <X> X apply(Function<T, X> function, X defaultValue);

		public void accept(Consumer<T> block);

		public <X> Nillable<X> map(Function<T, X> mapper);
	}

	public interface BaseData {
	}

	public interface BaseDataBuilder<T> {
		public T build();
	}
}
