// Generated by RSD - Do not modify
package at.bestsolution.quti.client.model;

public interface _Base {
	public interface BaseData {
	}

	public interface BaseDataBuilder<T> {
		public T build();
	}
}
