// Generated by RSD - Do not modify
package at.bestsolution.quti.client.jdkhttp.impl.model;

import jakarta.json.JsonObject;

import at.bestsolution.quti.client.model.EventView;

public abstract class EventViewDataImpl implements EventView.Data {
    public static EventView.Data of(JsonObject obj) {
        var descriminator = obj.getString("@type");
        return switch(descriminator) {
            case "single" -> new SingleEventViewDataImpl(obj);
            case "series-moved" -> new SeriesMovedEventViewDataImpl(obj);
            case "series" -> new SeriesEventViewDataImpl(obj);
            default -> throw new IllegalArgumentException("Unexpected value: %s".formatted(descriminator));
        };
    }
}