// Generated by RSD - Do not modify
package at.bestsolution.quti.client.dto;

public interface BaseDTO {
    public static record Nillable<T>(T value) {}

    public interface Builder {
        public BaseDTO build();
    }
}
