// Generated by RSD - Do not modify
package at.bestsolution.quti.client.dto;

public interface CalendarNewDTO extends BaseDTO {
    public String name();
    public String owner();

    public interface Builder extends BaseDTO.Builder {
        public Builder name(String name);
        public Builder owner(String owner);
        public CalendarNewDTO build();
    }
}
