// Generated by RSD - Do not modify
package at.bestsolution.quti.client.dto;

import java.util.List;

public interface EventViewFilterDTO extends BaseDTO {
    public String owner();
    public String title();
    public String description();
    public boolean fullday();
    public List<String> tags();

    public interface Builder extends BaseDTO.Builder {
        public Builder owner(String owner);
        public Builder title(String title);
        public Builder description(String description);
        public Builder fullday(boolean fullday);
        public Builder tags(List<String> tags);
        public EventViewFilterDTO build();
    }
}
