// Generated by RSD - Do not modify
package at.bestsolution.quti.client.dto;

public interface EventViewDTO extends BaseDTO {
    public enum Status {
        ACCEPTED,
        CANCELED,
    }

    public String key();
    public String calendarKey();
    public String title();
    public String description();
    public String owner();
    public Status status();
    public java.time.ZonedDateTime start();
    public java.time.ZonedDateTime end();
    public java.util.List<String> tags();
    public java.util.List<String> referencedCalendars();

    public interface Builder extends BaseDTO.Builder {
        public Builder key(String key);
        public Builder calendarKey(String calendarKey);
        public Builder title(String title);
        public Builder description(String description);
        public Builder owner(String owner);
        public Builder status(Status status);
        public Builder start(java.time.ZonedDateTime start);
        public Builder end(java.time.ZonedDateTime end);
        public Builder tags(java.util.List<String> tags);
        public Builder referencedCalendars(java.util.List<String> referencedCalendars);
        public EventViewDTO build();
    }

    public interface SingleEventViewDTO extends EventViewDTO {

        public interface Builder extends EventViewDTO.Builder {
            public Builder key(String key);
            public Builder calendarKey(String calendarKey);
            public Builder title(String title);
            public Builder description(String description);
            public Builder owner(String owner);
            public Builder status(Status status);
            public Builder start(java.time.ZonedDateTime start);
            public Builder end(java.time.ZonedDateTime end);
            public Builder tags(java.util.List<String> tags);
            public Builder referencedCalendars(java.util.List<String> referencedCalendars);
            public SingleEventViewDTO build();
        }
    }

    public interface SeriesMovedEventViewDTO extends EventViewDTO {
        public String masterEventKey();
        public java.time.ZonedDateTime originalStart();
        public java.time.ZonedDateTime originalEnd();

        public interface Builder extends EventViewDTO.Builder {
            public Builder masterEventKey(String masterEventKey);
            public Builder originalStart(java.time.ZonedDateTime originalStart);
            public Builder originalEnd(java.time.ZonedDateTime originalEnd);
            public Builder key(String key);
            public Builder calendarKey(String calendarKey);
            public Builder title(String title);
            public Builder description(String description);
            public Builder owner(String owner);
            public Builder status(Status status);
            public Builder start(java.time.ZonedDateTime start);
            public Builder end(java.time.ZonedDateTime end);
            public Builder tags(java.util.List<String> tags);
            public Builder referencedCalendars(java.util.List<String> referencedCalendars);
            public SeriesMovedEventViewDTO build();
        }
    }

    public interface SeriesEventViewDTO extends EventViewDTO {
        public String masterEventKey();

        public interface Builder extends EventViewDTO.Builder {
            public Builder masterEventKey(String masterEventKey);
            public Builder key(String key);
            public Builder calendarKey(String calendarKey);
            public Builder title(String title);
            public Builder description(String description);
            public Builder owner(String owner);
            public Builder status(Status status);
            public Builder start(java.time.ZonedDateTime start);
            public Builder end(java.time.ZonedDateTime end);
            public Builder tags(java.util.List<String> tags);
            public Builder referencedCalendars(java.util.List<String> referencedCalendars);
            public SeriesEventViewDTO build();
        }
    }
}
