// Generated by RSD - Do not modify
package at.bestsolution.quti.client.dto;

public interface EventRepeatDTO extends BaseDTO {
    public short interval();
    public java.time.LocalDate endDate();
    public java.time.ZoneId timeZone();

    public interface Builder extends BaseDTO.Builder {
        public Builder interval(short interval);
        public Builder endDate(java.time.LocalDate endDate);
        public Builder timeZone(java.time.ZoneId timeZone);
        public EventRepeatDTO build();
    }

    public interface EventRepeatDailyDTO extends EventRepeatDTO {

        public interface Builder extends EventRepeatDTO.Builder {
            public Builder interval(short interval);
            public Builder endDate(java.time.LocalDate endDate);
            public Builder timeZone(java.time.ZoneId timeZone);
            public EventRepeatDailyDTO build();
        }
    }

    public interface EventRepeatWeeklyDTO extends EventRepeatDTO {
        public java.util.List<java.time.DayOfWeek> daysOfWeek();

        public interface Builder extends EventRepeatDTO.Builder {
            public Builder daysOfWeek(java.util.List<java.time.DayOfWeek> daysOfWeek);
            public Builder interval(short interval);
            public Builder endDate(java.time.LocalDate endDate);
            public Builder timeZone(java.time.ZoneId timeZone);
            public EventRepeatWeeklyDTO build();
        }
    }

    public interface EventRepeatAbsoluteMonthlyDTO extends EventRepeatDTO {
        public short dayOfMonth();

        public interface Builder extends EventRepeatDTO.Builder {
            public Builder dayOfMonth(short dayOfMonth);
            public Builder interval(short interval);
            public Builder endDate(java.time.LocalDate endDate);
            public Builder timeZone(java.time.ZoneId timeZone);
            public EventRepeatAbsoluteMonthlyDTO build();
        }
    }

    public interface EventRepeatAbsoluteYearlyDTO extends EventRepeatDTO {
        public java.time.Month month();

        public interface Builder extends EventRepeatDTO.Builder {
            public Builder month(java.time.Month month);
            public Builder interval(short interval);
            public Builder endDate(java.time.LocalDate endDate);
            public Builder timeZone(java.time.ZoneId timeZone);
            public EventRepeatAbsoluteYearlyDTO build();
        }
    }

    public interface EventRepeatRelativeMonthlyDTO extends EventRepeatDTO {
        public java.util.List<java.time.DayOfWeek> daysOfWeek();

        public interface Builder extends EventRepeatDTO.Builder {
            public Builder daysOfWeek(java.util.List<java.time.DayOfWeek> daysOfWeek);
            public Builder interval(short interval);
            public Builder endDate(java.time.LocalDate endDate);
            public Builder timeZone(java.time.ZoneId timeZone);
            public EventRepeatRelativeMonthlyDTO build();
        }
    }

    public interface EventRepeatRelativeYearlyDTO extends EventRepeatDTO {
        public java.util.List<java.time.DayOfWeek> daysOfWeek();
        public java.time.Month month();

        public interface Builder extends EventRepeatDTO.Builder {
            public Builder daysOfWeek(java.util.List<java.time.DayOfWeek> daysOfWeek);
            public Builder month(java.time.Month month);
            public Builder interval(short interval);
            public Builder endDate(java.time.LocalDate endDate);
            public Builder timeZone(java.time.ZoneId timeZone);
            public EventRepeatRelativeYearlyDTO build();
        }
    }
}
