// Generated by RSD - Do not modify
package at.bestsolution.quti.client.dto;

public interface EventDTO extends BaseDTO {
    public String key();
    public String title();
    public String description();
    public java.time.ZonedDateTime start();
    public java.time.ZonedDateTime end();
    public boolean fullday();
    public EventRepeatDTO repeat();
    public java.util.List<String> tags();
    public java.util.List<String> referencedCalendars();

    public interface Builder extends BaseDTO.Builder {
        public Builder key(String key);
        public Builder title(String title);
        public Builder description(String description);
        public Builder start(java.time.ZonedDateTime start);
        public Builder end(java.time.ZonedDateTime end);
        public Builder fullday(boolean fullday);
        public Builder repeat(EventRepeatDTO repeat);
        public Builder tags(java.util.List<String> tags);
        public Builder referencedCalendars(java.util.List<String> referencedCalendars);
        public <T extends EventRepeatDTO.Builder> Builder withRepeat(Class<T> clazz, java.util.function.Function<T, EventRepeatDTO> block);
        public EventDTO build();
    }
}
