// Generated by RSD - Do not modify
package at.bestsolution.quti.client.dto;

public interface MixinCalendarDataDTO {
	public interface Builder {
	}

	/**
	 * Name of the calendar
	 */
	public String name();

	/**
	 * Owner of the calendar
	 */
	public String owner();
}
