// Generated by RSD - Do not modify
package at.bestsolution.quti.client.dto;

import java.time.ZonedDateTime;
import java.util.List;

public interface SingleEventViewDTO extends EventViewDTO, MixinEventViewDataDTO {

    public interface Builder extends EventViewDTO.Builder, MixinEventViewDataDTO.Builder {
        public Builder key(String key);
        public Builder calendarKey(String calendarKey);
        public Builder title(String title);
        public Builder description(String description);
        public Builder owner(String owner);
        public Builder status(Status status);
        public Builder start(ZonedDateTime start);
        public Builder end(ZonedDateTime end);
        public Builder tags(List<String> tags);
        public Builder referencedCalendars(List<String> referencedCalendars);
        public SingleEventViewDTO build();
    }
}
